name: iconfont
description: Dart library to generate Dart model class from IconFont files.
version: 2.0.0-pre1
homepage: https://github.com/chuanci/iconfont

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  args: ^2.0.0
  http: ^0.13.4
  path: ^1.8.2

executables:
  iconfont: